### ISSUE TITLE
Problems with using rintrojs inside shiny modules

### ISSUE THREAD

**Issue by thercast** [carlganz/rintrojs#15]
I'm helping to develop a complex shiny application that makes use of [modules](http://shiny.rstudio.com/articles/modules.html) to streamline the development.  We'd really like to use `rintrojs` as our way of providing in-app help.  But it does not work correctly when included inside the UI portion of a shiny module, through it works as expected when it is only in the non-module UI portion.  Below are examples of each case:

## Working example

```
library(shiny)
library(rintrojs)
selectorUI <- function(id) {
  ns <- NS(id)

    selectizeInput(inputId = ns('select'),
                   label = 'Make a choice:',
                   choices = c('Option one', 'Option two'))

}
ui <- shinyUI(fluidPage(
  introjsUI(),

  introBox(
    titlePanel("Old Faithful Geyser Data"),
    data.step = 1,
    data.intro = "this is a try" 
  ),


  selectorUI('id1'),
  conditionalPanel(condition = "input['id1-select'] == 'Option one'",
                   p('Option one is selected.'))
  ,actionButton("help", "Press for instructions")
))

server <- shinyServer(function(input, output, session) {


  observeEvent(input$help,
               introjs(session, options = list("nextLabel"="Onwards and Upwards",
                                               "prevLabel"="Did you forget something?",
                                               "skipLabel"="Don't be a quitter"),
                       events = list("oncomplete"='alert("Glad that is over")'))
  )

})

shinyApp(ui = ui, server = server)
```

## Non-working example

Error is `ERROR: could not find function "ns"` when running the `ui` portion of code.

```
library(shiny)
library(rintrojs)
selectorUI <- function(id) {
  ns <- NS(id)
  introBox(
    selectizeInput(inputId = ns('select'),
                   label = 'Make a choice:',
                   choices = c('Option one', 'Option two')),
    data.step = 2,
    data.intro = "inside of inside"
  )

}

ui <- shinyUI(fluidPage(
  introjsUI(),

  introBox(
    titlePanel("Old Faithful Geyser Data"),
    data.step = 1,
    data.intro = "this is a try" 
  ),

  selectorUI('id1'),
  conditionalPanel(condition = "input['id1-select'] == 'Option one'",
                   p('Option one is selected.'))
  ,actionButton("help", "Press for instructions")
))

server <- shinyServer(function(input, output, session) {


  observeEvent(input$help,
               introjs(session, options = list("nextLabel"="Onwards and Upwards",
                                               "prevLabel"="Did you forget something?",
                                               "skipLabel"="Don't be a quitter"),
                       events = list("oncomplete"='alert("Glad that is over")'))
  )

})

shinyApp(ui = ui, server = server)
```

**Comment by carlganz** [comment]
Thanks for the report. This appears to be an issue with environments. I am working on a solution.

**Comment by carlganz** [comment]
I believe the problem is fixed now. Please download the latest version from github `devtools::install_github("carlganz/rintrojs")`, and let me know if you find any problems. 

Your feedback is greatly appreciated. Thanks again for reporting the issue.

**Comment by thercast** [comment]
Sorry for replying back late but the fix worked flawlessly for our apps.  Thanks so much for your quick response!

**Comment by PsychlytxTD** [comment]
Trying to use rintrojs in a production-grade shiny app using Golem and modules. Can't get it working:

```
  tagList(
    uiOutput(ns("outcome_measure_interface")),

      div(id = ns("submit_div"),
          fluidRow(

            column(width = 4, offset = 4,

                   rintrojs::introBox(
                   div(id = ns("box"),
                   actionButton(ns("submit_scores"), "Submit Measure Responses", class = "submit_button")
                   ),
                   data.step = 1,
                   data.intro = "This is the title panel"
            )

            ))
      )

  )
```

Calling `rintrojs::introjsUI()` in  app_ui.

Unless I can resolve this soon I'll have to find something else.

**Comment by carlganz** [comment]
Note: strongly discourage you from going into Github issues, mentioning your app is production-grade, and then making threats if this can't be resolved "soon". Please go ahead and use another library if this is how you speak to open source maintainers. 

You've shared part of a shiny module which is not a reproducible example. Please provide a full reproducible example, and explain what you expect to happen, and what actually happens. Where do you call `introjs(session)` in the server to initiate the intro?

Thanks

**Comment by PsychlytxTD** [comment]
Hi carlganz, fair call. Looking at my message, it's clearly brusque and unhelpful. I apologise unreservedly. I think I was actually frustrated about something else and allowed it to spill out here. I'll have another look (sleeping on things works wonders) and if I still can't resolve it, will post a full reproducible example. 

Tim
